version: "3.9"
services:
    web:
        build: .
        ports:
            - "8000:80"
        depends_on:
            - db
    db:
        image: "mcr.microsoft.com/mssql/server"
        user: root
        ports: 
            - 1433:1433
        volumes:
            - sql_data:/var/opt/mssql/data
            - sql_logs:/var/opt/mssql/log 
            - sql_secrets:/var/opt/mssql/secrets
        environment:
            SA_PASSWORD: "Your_password123"
            ACCEPT_EULA: "Y"
    web-ui:
        build: ./webclient/
        ports: 
            - 4200:80
        links:
            - web


volumes:
    sql_data:
    sql_logs:
    sql_secrets: